version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    #ports:
    #  - "4000:3000"
    stdin_open: true
  nginx:
    restart: always #no, on-failure, unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./proxy-nginx
    ports:
      - "3000:80"
  backend:    #node
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
#  mysql:
#    build: ./mysql    #Dockerfile.dev가 아니므로 자동으로 Dockerfile을 찾음
#    restart: unless-stopped
#    container_name: app_mysql
#    ports:
#      - "3307:3306"
#    volumes:
#      - ./mysql/mysql_data:/var/lib/mysql
#      - ./mysql/sqls:/docer-entrypoint-initdb.d/
#    environment:
#      MYSQL_ROOT_PASSWORD: awdsd123
#      MYSQL_DATABASE: myapp